# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-02-05 07:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='generate_options',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('institute_name', models.CharField(default='', max_length=1000)),
                ('subject', models.CharField(default='', max_length=1000)),
                ('level', models.IntegerField(choices=[(b'1', b'1'), (b'2', b'2'), (b'3', b'3'), (b'4', b'4'), (b'5', b'5'), (b'6', b'6'), (b'7', b'7'), (b'8', b'8'), (b'9', b'9'), (b'10', b'10')], default='')),
                ('group_a_question', models.IntegerField(choices=[(b'12', b'12'), (b'7', b'7'), (b'10', b'10')], default='')),
                ('group_a_cq', models.IntegerField(choices=[(b'5', b'5'), (b'10', b'10'), (b'8', b'8')], default='')),
                ('group_b_question', models.IntegerField(choices=[(b'12', b'12'), (b'8', b'8'), (b'6', b'6')], default='')),
                ('group_b_qc', models.IntegerField(choices=[(b'10', b'10'), (b'6', b'6'), (b'4', b'4')], default='')),
                ('group_c_question', models.IntegerField(choices=[(b'3', b'3'), (b'4', b'4')], default='')),
                ('group_c_qc', models.IntegerField(choices=[(b'2', b'2')], default='')),
            ],
        ),
    ]
