# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-01-21 16:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='admin_login',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(default='', max_length=100)),
                ('password', models.CharField(default='', max_length=30)),
                ('institute_name', models.CharField(default='', max_length=30)),
                ('address', models.CharField(default='', max_length=500)),
            ],
        ),
    ]
