# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2020-04-22 13:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='login_details',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(default='', max_length=100)),
                ('password', models.CharField(default='', max_length=50)),
            ],
        ),
        migrations.DeleteModel(
            name='login_forms',
        ),
    ]
