# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-01-29 13:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='question_details',
            fields=[
                ('question_id', models.AutoField(primary_key=True, serialize=False)),
                ('question', models.CharField(default='', max_length=1000)),
                ('subject', models.CharField(default='', max_length=1000)),
                ('level', models.IntegerField(default='')),
                ('group', models.CharField(choices=[(b'A', b'Group A'), (b'B', b'Group B'), (b'C', b'Group C')], default='', max_length=30)),
                ('question_weight', models.CharField(choices=[(b'5', b'5'), (b'2', b'2'), (b'10', b'10')], default='', max_length=30)),
                ('question_type', models.CharField(choices=[(b'VSQ', b'Very short question'), (b'SQ', b'Short question'), (b'LQ', b'Long question')], default='', max_length=30)),
            ],
        ),
    ]
