# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-01-30 06:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('add_question_paper', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question_details',
            name='group',
            field=models.CharField(choices=[(b'Group A', b'Group A'), (b'Group B', b'Group B'), (b'Group C', b'Group C')], default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='question_details',
            name='question_type',
            field=models.CharField(choices=[(b'Very short question', b'Very short question'), (b'Short question', b'Short question'), (b'Long question', b'Long question')], default='', max_length=30),
        ),
    ]
